export const API_KEY = process.env.REACT_APP_API_KEY;

export const FETCH_DATA = "FETCH_DATA";
export const DATA_FETCHED = "DATA_FETCHED";
export const IS_FETCHING = "IS_FETCHING";
export const MARK_FAVOURITE = "MARK_FAVOURITE";
export const ADD_FAV_TO_LIST = "ADD_FAV_TO_LIST";
export const TOGGLE_LOADING_INDICATOR = "TOGGLE_LOADING_INDICATOR";
export const TOGGLE_ERROR_INDICATOR = "TOGGLE_ERROR_INDICATOR";
